<?php
if(isset($_SESSION['Code']))
		{
			$code=$_SESSION['Code'];
	$see=mysqli_query($conn, "SELECT *FROM `account` WHERE `Number`='$code'");
		if($fee=mysqli_num_rows($see)){
		$ree=mysqli_fetch_assoc($see);
			$nom=$ree['nom'];
			$postnom=$ree['postnom'];
			$prenom=$ree['prenom'];
			$lieu=$ree['lieu'];
			$date=date("d-m-Y", strtotime($ree['date']));
			$pere=$ree['pere'];
			$pviva=$ree['pviva'];
			$mere=$ree['mere'];
			$mviva=$ree['mviva'];
			$photo=$ree['photo'];
			$grandpere=$ree['grandpere'];
			$gpviva=$ree['gpviva'];
			$grandmere=$ree['grandmere'];
			$gmviva=$ree['gmviva'];
			$sexe=$ree['sexe'];
			$langue=$ree['langue'];
			$etude=$ree['etude'];
			$civil=$ree['civil'];
			$conjoint=$ree['conjoint'];
			$cviva=$ree['cviva'];
			$enfant=$ree['enfant'];
			$profession=$ree['profession'];
			$permis=$ree['permis'];
			$cata=$ree['cata'];
			$catb=$ree['catb'];
			$catc=$ree['catc'];
			$catd=$ree['catd'];
			$cate=$ree['cate'];
			$nationalite=$ree['nationalite'];
			$pays=$ree['pays'];
			$province=$ree['province'];
			$territoire=$ree['territoire'];
			$secteur=$ree['secteur'];
			$collectivite=$ree['collectivite'];
			$groupement=$ree['groupement'];
			$village=$ree['village'];
			$type=$ree['type'];
			$idno=$ree['idno'];
			$delieu=$ree['delieu'];
			$carte=$ree['carte'];
			$delivrance=$ree['delivrance'];
			$ano=$ree['ano'];
			$aavenue=$ree['aavenue'];
			$aquartier=$ree['aquartier'];
			$acommune=$ree['acommune'];
			$aville=$ree['aville'];
			$asecteur=$ree['asecteur'];
			$aprovince=$ree['aprovince'];
			$contact=$ree['contact'];
			$email=$ree['email'];
			$rnom=$ree['rnom'];
			$rlieu=$ree['rlieu'];
			$rphone=$ree['rphone'];
			$rno=$ree['rno'];
			$ravenue=$ree['ravenue'];
			$rquartier=$ree['rquartier'];
			$rcommune=$ree['rcommune'];
			$rville=$ree['rville'];
			$rsecteur=$ree['rsecteur'];
			$rprovince=$ree['rprovince'];
			$marque=$ree['marque'];
			$fabrication=$ree['fabrication'];
			$chassie=$ree['chassie'];
			$couleur=$ree['couleur'];
			$plaque=$ree['plaque'];
			$pnom=$ree['pnom'];
			$pno=$ree['pno'];
			$pavenue=$ree['pavenue'];
			$pquartier=$ree['pquartier'];
			$pville=$ree['pville'];
			$psecteur=$ree['psecteur'];
			$pprovince=$ree['pprovince'];
			$pcontact=$ree['pcontact'];
			$pcommune=$ree['pcommune'];
			$pemail=$ree['pemail'];
			$photo=$ree['photo'];
			$upda=$ree['upda'];
			if($photo)
				$photo="files/$photo";
			else
				$photo="imgs/-text.png";

			$ca=$cb=$cc=$cd=$ce='';

			if($civil=='Marié')
				$ca='selected';
			if($civil=='Mariée')
				$cb='selected';
			if($civil=='Veuve')
				$cc='selected';
			if($civil=='Divorcé')
				$cd='selected';
			if($civil=='Célibataire')
				$ce='selected';

			$a=$b=$c=$d=$e='';

			if($cata=='A')
				$a='checked';
			if($catb=='B')
				$b='checked';
			if($catc=='C')
				$c='checked';
			if($catd=='D')
				$d='checked';
			if($cate=='E')
				$e='checked';
		}
		}
		?>